// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWHq2n8i5-bWqsf2ZB9Fy4dUrl7CsB3Q',
    appId: '1:96688632630:web:104895afa3e1383eacb997',
    messagingSenderId: '96688632630',
    projectId: 'todo-app-c11-744d4',
    authDomain: 'todo-app-c11-744d4.firebaseapp.com',
    storageBucket: 'todo-app-c11-744d4.appspot.com',
    measurementId: 'G-YSYDR8EF6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0QSMPRITid7Dg18CvrMbKqBfbroNxCAI',
    appId: '1:96688632630:android:3249f088753a0910acb997',
    messagingSenderId: '96688632630',
    projectId: 'todo-app-c11-744d4',
    storageBucket: 'todo-app-c11-744d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOmuwh7Z2pdw9NmB-NzQYxNCOIa8UuLQ',
    appId: '1:96688632630:ios:347684d7dfc7d6d7acb997',
    messagingSenderId: '96688632630',
    projectId: 'todo-app-c11-744d4',
    storageBucket: 'todo-app-c11-744d4.appspot.com',
    iosBundleId: 'com.example.todoAppC11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFOmuwh7Z2pdw9NmB-NzQYxNCOIa8UuLQ',
    appId: '1:96688632630:ios:347684d7dfc7d6d7acb997',
    messagingSenderId: '96688632630',
    projectId: 'todo-app-c11-744d4',
    storageBucket: 'todo-app-c11-744d4.appspot.com',
    iosBundleId: 'com.example.todoAppC11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOWHq2n8i5-bWqsf2ZB9Fy4dUrl7CsB3Q',
    appId: '1:96688632630:web:1caea50e63650874acb997',
    messagingSenderId: '96688632630',
    projectId: 'todo-app-c11-744d4',
    authDomain: 'todo-app-c11-744d4.firebaseapp.com',
    storageBucket: 'todo-app-c11-744d4.appspot.com',
    measurementId: 'G-6DNSMBKVSR',
  );
}
